import { PropertyData, CustomAIAnalysisResult, ComprehensiveAnalysisResult } from "../../types";
import { optimizePropertyForAi, optimizeVisualForAi } from "../../utils/aiOptimization";

export const getChatContext = (property: PropertyData, visual: CustomAIAnalysisResult | null, comprehensive: ComprehensiveAnalysisResult | null) => {
    // 1. Optimize raw property data
    const optimizedProperty = optimizePropertyForAi(property);

    // 2. Optimize visual data but preserve image_by_image_analysis for visual grounding
    let optimizedVisual: any = visual ? { ...optimizeVisualForAi(visual) } : null;
    if (visual?.image_by_image_analysis && optimizedVisual) {
        optimizedVisual.imageAnalysis = visual.image_by_image_analysis.map((img, idx) => ({
            index: idx,
            summary: img.analysis.slice(0, 150) + "..." // Truncate to save tokens
        }));
    }

    return {
        ...optimizedProperty,
        visualIntelligence: optimizedVisual || "Visual analysis not yet generated by the user.",
        communityPulse: visual?.community_pulse || comprehensive?.detailed_analysis?.community_pulse || "Community pulse data not yet fully integrated for this area.",
        propertyInvestment: visual?.property_investment || "Investment yield data not yet available.",
        generalMarketIntelligence: visual?.general_market_intelligence ? (({ web_sources, ...rest }) => rest)(visual.general_market_intelligence as any) : "General market trends not yet analyzed.",
        narrativeReport: comprehensive ? {
            summary: comprehensive.summary,
            detailedAnalysis: comprehensive.detailed_analysis,
            strategicInsights: comprehensive.strategic_insights,
            risksAndConsiderations: comprehensive.risks_considerations
        } : "Comprehensive narrative not yet generated by the user."
    };
};

export const getChatInstruction = (intelligenceContext: any) => `You are Zyphe AI, an elite property concierge. You have absolute, deep-link access to the following property intelligence data.
        
          PROPERTY INTELLIGENCE KNOWLEDGE BASE:
          ${JSON.stringify(intelligenceContext, null, 2)}
          
          YOUR MISSION:
          1. Answer the user's current question accurately using ONLY the Knowledge Base above. If the information IS in the Knowledge Base, you MUST respond in friendly, conversational natural language. Do NOT use JSON if you can answer the question.
          2. ONLY if the information is Genuinely Missing and not found in any section of the Knowledge Base, you must recommend a source. In this specific and only case, respond ONLY with a JSON object in this format:
             {
               "routing": "MISSING",
               "source": "images" | "search" | "not_found",
               "image_indices": [index of images from visualIntelligence.imageAnalysis if relevant],
               "reasoning": "brief explanation"
             }
             - Use "images" if the detail is likely visible in the property photos.
             - Use "search" if it's a general fact likely discoverable online.
             - Use "not_found" if unavailable or private.
          3. Be conversational but extremely precise. Use "bold" for key numbers and specs.
          4. If asked about safety, neighborhood vibe, or local resident sentiment, refer directly to the 'communityPulse' section.
          5. If asked about mobility, walkability, or transit, check the 'mobility' field.
          6. If asked about technical specs like roof type or foundation, check the 'specifications.details' field.
          7. Always maintain a helpful, professional "Concierge" tone.
          8. If asked about market trends, appreciation, or economic growth, refer to 'generalMarketIntelligence'.
          9. If asked about rental yields (STR/LTR) or specific investment numbers, refer to 'propertyInvestment'.
          10. Use 'visualIntelligence' (including 'imageAnalysis' for specific photo observations) for stylistic or interior design questions.
          11. Note: You only see the current user prompt to maintain high speed. Treat every request as a fresh inquiry about the property data provided.`;
