import React, { useState, useEffect } from 'react';
import { Lead, Transaction } from '../../types';
import { createTransaction, getTransactions, getTransactionByClientId, updateTransaction, getTransactionTasks, updateTask } from '../../services/firebaseService';
import GanttChart from './GanttChart';
import { ChecklistCategory } from '../../types/transaction';
import { getInitialCategories } from '../../services/transactionService';


interface Props {
    lead: Lead;
    realtorId: string;
}

const TransactionTab: React.FC<Props> = ({ lead, realtorId }) => {
    const [transaction, setTransaction] = useState<Transaction | null>(null);
    const [loading, setLoading] = useState(false);
    const [isCreating, setIsCreating] = useState(false);
    const [categories, setCategories] = useState<ChecklistCategory[]>(getInitialCategories(lead.leadType === 'Seller' ? 'Seller' : 'Buyer'));

    const fetchTransaction = async () => {
        if (!realtorId || !lead?.id) return;
        setLoading(true);
        try {
            // 1. Precise Query by clientId (Optimized)
            let match = await getTransactionByClientId(lead.id, realtorId);

            // 2. Fallback: Search all realtor transactions if no ID link exists yet (Legacy/Fallback)
            if (!match) {
                const allTransactions = await getTransactions(realtorId);
                match = allTransactions.find(t =>
                    t.property?.address === (lead.subjectProperty || lead.propertyAddress)
                );
            }

            setTransaction(match || null);

            // Hydrate categories from CRMTasks collection
            if (match) {
                const txType = match.type === 'SELL' ? 'Seller' : 'Buyer';
                const blueprint = getInitialCategories(txType);
                const dbTasks = await getTransactionTasks(match.id, realtorId);

                // Group standalone tasks by their categoryId
                const tasksByCategory = new Map<string, any[]>();
                dbTasks.forEach(task => {
                    const catId = task.categoryId || 'uncategorized';
                    if (!tasksByCategory.has(catId)) tasksByCategory.set(catId, []);
                    tasksByCategory.get(catId)?.push({
                        id: task.id,
                        name: task.name,
                        status: task.status as any,
                        comments: task.comment || '',
                        startDate: task.startDate,
                        dueDate: task.dueDate,
                        dependsOn: task.dependsOn || [],
                        durationDays: task.durationDays || 1
                    });
                });

                // Reconstruct the categories using the blueprint structure but DB task data
                const hydratedCats = blueprint.map(cat => ({
                    ...cat,
                    tasks: tasksByCategory.get(cat.id) || []
                })).filter(cat => cat.tasks.length > 0 || cat.id === 'c1'); // Show c1 even if empty, hide others if no tasks

                setCategories(hydratedCats as any);
            }
        } catch (error) {
            console.error("Error fetching transaction:", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchTransaction();
    }, [lead, realtorId]);

    const handleCreateTransaction = async () => {
        setIsCreating(true);
        try {
            const initialCats = getInitialCategories(lead.leadType === 'Seller' ? 'Seller' : 'Buyer');
            const newTransaction: Transaction = {
                id: '', // Auto-generated by createTransaction
                realtorId,
                clientId: lead.id,
                type: lead.leadType === 'Buyer' ? 'BUY' : lead.leadType === 'Seller' ? 'SELL' : 'OTHER',
                status: 'DRAFT',
                //TODO : fix AJ
                property: {
                    address: lead.subjectProperty || lead.propertyAddress || 'New Property',
                    zpid: lead.zpid
                },
                purchase_price: 0,
                commission: '0%',
                apn: '',
                state: 'CA',
                checklist: [], // Will be populated atomically by createTransaction
                important_dates: {},
                created_at: new Date(),
                updated_at: new Date()
            };

            const createdTx = await createTransaction(newTransaction, initialCats);
            if (!createdTx) throw new Error("Failed to create transaction record.");

            setTransaction(createdTx);
            setCategories(createdTx.checklist as any);

        } catch (error) {
            console.error("Error creating transaction:", error);
        } finally {
            setIsCreating(false);
        }
    };

    const handleUpdateTaskStatus = async (catId: string, taskId: string, status: 'Pending' | 'Completed' | 'Rejected') => {
        // Update local state for immediate UI response
        setCategories(prev => prev.map(cat => {
            if (cat.id !== catId) return cat;
            return {
                ...cat,
                tasks: cat.tasks.map(t => t.id === taskId ? { ...t, status } : t)
            };
        }));

        // Persist change to CRMTasks collection (Source of Truth)
        try {
            await updateTask(taskId, { status: status as any }, transaction?.id);
        } catch (err) {
            console.error("Error updating task status:", err);
        }
    };

    const handleAddTaskComment = async (catId: string, taskId: string, comment: string) => {
        // Update local state for immediate UI response
        setCategories(prev => prev.map(cat => {
            if (cat.id !== catId) return cat;
            return {
                ...cat,
                tasks: cat.tasks.map(t => t.id === taskId ? { ...t, comments: comment } : t)
            };
        }));

        // Persist change to CRMTasks collection (Source of Truth)
        try {
            await updateTask(taskId, { comment }, transaction?.id);
        } catch (err) {
            console.error("Error adding task comment:", err);
        }
    };

    const handleUpdateTask = async (catId: string, taskId: string, updates: { name?: string; comment?: string; startDate?: Date; dueDate?: Date }) => {
        // Update local state for immediate UI response
        setCategories(prev => prev.map(cat => {
            if (cat.id !== catId) return cat;
            return {
                ...cat,
                tasks: cat.tasks.map(t => {
                    if (t.id === taskId) {
                        return {
                            ...t,
                            name: updates.name ?? t.name,
                            comments: updates.comment ?? t.comments,
                            startDate: updates.startDate ?? t.startDate,
                            dueDate: updates.dueDate ?? t.dueDate
                        };
                    }
                    return t;
                })
            };
        }));

        // Persist change to CRMTasks collection
        try {
            await updateTask(taskId, {
                name: updates.name,
                comment: updates.comment,
                startDate: updates.startDate,
                dueDate: updates.dueDate
            }, transaction?.id);
        } catch (err) {
            console.error("Error updating task details:", err);
        }
    };

    if (loading) {
        return <div className="p-10 text-center text-slate-400">Loading transaction details...</div>;
    }

    if (!transaction) {
        const isClosingStage = lead.funnelStage === 'Contract';

        return (
            <div className="flex flex-col items-center justify-center p-12 bg-white rounded-[2.5rem] border border-slate-200/60 shadow-xl shadow-indigo-500/5">
                <div className="w-20 h-20 rounded-3xl bg-indigo-50 flex items-center justify-center mb-6">
                    <i className="fa-solid fa-file-signature text-3xl text-indigo-500"></i>
                </div>
                <h3 className="text-xl font-black text-slate-900 mb-2">No Transaction Record</h3>
                <p className="text-slate-500 text-center max-w-sm mb-8">
                    {isClosingStage
                        ? `Start a new transaction record for ${lead.firstName} to track documents, dates, and signers.`
                        : `Transactions can only be managed for leads in the "Closing" stage. Move ${lead.firstName} to the Contract stage to begin.`
                    }
                </p>
                <button
                    onClick={handleCreateTransaction}
                    disabled={isCreating || !isClosingStage}
                    className={`px-8 py-4 text-white rounded-2xl text-xs font-black uppercase tracking-widest shadow-lg transition-all ${isClosingStage
                        ? 'bg-indigo-600 hover:bg-indigo-700 shadow-indigo-600/20'
                        : 'bg-slate-300 cursor-not-allowed shadow-none'
                        }`}
                >
                    {isCreating ? 'Creating...' : 'Initialize Transaction'}
                </button>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {/* Property Side */}
                <div className="p-4 bg-slate-50/50 rounded-2xl border border-slate-100/60">
                    <div className="flex items-center gap-2 mb-2">
                        <div className="w-5 h-5 rounded-md bg-white border border-slate-200 flex items-center justify-center">
                            <i className="fa-solid fa-house text-slate-400 text-[9px]"></i>
                        </div>
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Property Info</span>
                    </div>
                    <div className="space-y-2">
                        <div>
                            <label className="block text-[8px] font-bold text-slate-400 uppercase mb-0.5">Address</label>
                            <div className="text-xs font-bold text-slate-800 leading-tight">{transaction.property?.address || 'N/A'}</div>
                        </div>
                        <div className="grid grid-cols-2 gap-2">
                            <div>
                                <label className="block text-[8px] font-bold text-slate-400 uppercase mb-0.5">Price</label>
                                <div className="text-xs font-bold text-slate-800">
                                    {transaction.purchase_price ? `$${transaction.purchase_price.toLocaleString()}` : '--'}
                                </div>
                            </div>
                            <div>
                                <label className="block text-[8px] font-bold text-slate-400 uppercase mb-0.5">Comm.</label>
                                <div className="text-xs font-bold text-emerald-600">
                                    {transaction.commission || '--'}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Dates Side */}
                <div className="p-4 bg-slate-50/50 rounded-2xl border border-slate-100/60">
                    <div className="flex items-center gap-2 mb-2">
                        <div className="w-5 h-5 rounded-md bg-white border border-slate-200 flex items-center justify-center">
                            <i className="fa-solid fa-calendar-days text-slate-400 text-[9px]"></i>
                        </div>
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Key Dates</span>
                    </div>
                    <div className="space-y-2">
                        <div className="grid grid-cols-2 gap-2">
                            <div>
                                <label className="block text-[8px] font-bold text-slate-400 uppercase mb-0.5">Acceptance</label>
                                <div className="text-xs font-bold text-slate-800">
                                    {transaction.important_dates?.acceptance_date?.toDate ? new Date(transaction.important_dates.acceptance_date.toDate()).toLocaleDateString() : (transaction.important_dates?.acceptance_date ? new Date(transaction.important_dates.acceptance_date).toLocaleDateString() : '--')}
                                </div>
                            </div>
                            <div>
                                <label className="block text-[8px] font-bold text-slate-400 uppercase mb-0.5">Closing</label>
                                <div className="text-xs font-bold text-indigo-600">
                                    {transaction.close_of_escrow_date?.toDate ? new Date(transaction.close_of_escrow_date.toDate()).toLocaleDateString() : (transaction.close_of_escrow_date ? new Date(transaction.close_of_escrow_date).toLocaleDateString() : '--')}
                                </div>
                            </div>
                        </div>
                        <div>
                            <label className="block text-[8px] font-bold text-slate-400 uppercase mb-0.5">Contingency removal</label>
                            <div className="text-xs font-bold text-slate-800">
                                {transaction.important_dates?.contingency_removal_date?.toDate ? new Date(transaction.important_dates.contingency_removal_date.toDate()).toLocaleDateString() : (transaction.important_dates?.contingency_removal_date ? new Date(transaction.important_dates.contingency_removal_date).toLocaleDateString() : '--')}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {(() => {
                const txStartDate = transaction?.important_dates?.acceptance_date?.toDate
                    ? transaction.important_dates.acceptance_date.toDate()
                    : (transaction?.important_dates?.acceptance_date ? new Date(transaction.important_dates.acceptance_date) : undefined);

                return (
                    <GanttChart
                        categories={categories}
                        startDate={txStartDate}
                        onTaskStatusChange={handleUpdateTaskStatus}
                        onAddComment={handleAddTaskComment}
                        onUpdateTask={handleUpdateTask}
                    />
                );
            })()}
        </div>
    );
};

export default TransactionTab;
