export const GUIDE_DATA = [
    {
        topicSlug: 'hoa',
        title: 'HOA & Community Rules',
        items: [
            { id: 'h1', title: 'What happens if HOA fines go unpaid in California?', slug: 'what-happens-if-hoa-fines-go-unpaid-california' },
            { id: 'h2', title: 'Can an HOA place a lien on your home in CA?', slug: 'hoa-lien-process-california' },
            { id: 'h3', title: 'How long before HOA can foreclose in California?', slug: 'hoa-foreclosure-timeline-california' },
            { id: 'h4', title: 'Can HOA increase dues without homeowner approval?', slug: 'can-hoa-increase-dues-without-homeowner-approval' },
            { id: 'h5', title: 'What is an HOA special assessment?', slug: 'what-is-an-hoa-special-assessment' },
            { id: 'h6', title: 'Can HOA deny exterior changes?', slug: 'can-hoa-deny-exterior-changes' },
            { id: 'h7', title: 'Can HOA restrict rentals in California?', slug: 'can-hoa-restrict-rentals-in-california' },
            { id: 'h8', title: 'What happens if you ignore HOA violation notices?', slug: 'what-happens-if-you-ignore-hoa-violation-notices' },
            { id: 'h9', title: 'Can HOA tow your car from your driveway?', slug: 'can-hoa-tow-your-car-from-your-driveway' },
            { id: 'h10', title: 'HOA dispute process explained', slug: 'hoa-dispute-process-explained' },
            { id: 'h11', title: 'Can HOA fine without notice?', slug: 'can-hoa-fine-without-notice' },
            { id: 'h12', title: 'What rights do homeowners have against HOA?', slug: 'what-rights-do-homeowners-have-against-hoa' },
            { id: 'h13', title: 'How HOA collections work', slug: 'how-hoa-collections-work' },
            { id: 'h14', title: 'What happens after HOA sends a demand letter?', slug: 'what-happens-after-hoa-sends-a-demand-letter' },
            { id: 'h15', title: 'Can HOA charge late fees?', slug: 'can-hoa-charge-late-fees' },
            { id: 'h16', title: 'HOA vs homeowner insurance responsibility', slug: 'hoa-vs-homeowner-insurance-responsibility' },
            { id: 'h17', title: 'What documents govern HOA authority?', slug: 'what-documents-govern-hoa-authority' },
            { id: 'h18', title: 'Can HOA foreclose for unpaid dues?', slug: 'can-hoa-foreclose-for-unpaid-dues' },
            { id: 'h19', title: 'How to request HOA records', slug: 'how-to-request-hoa-records' },
            { id: 'h20', title: 'HOA election and board powers explained', slug: 'hoa-election-and-board-powers-explained' },
        ]
    },
    {
        topicSlug: 'insurance',
        title: 'Homeowners Insurance',
        items: [
            { id: 'i1', title: 'Why was my homeowners insurance claim denied?', slug: 'homeowners-insurance-claim-denied' },
            { id: 'i2', title: 'What happens after filing a homeowners claim?', slug: 'what-happens-after-filing-a-homeowners-claim' },
            { id: 'i3', title: 'How long does an insurance investigation take?', slug: 'insurance-adjuster-investigation-timeline' },
            { id: 'i4', title: 'What does an insurance adjuster do?', slug: 'what-does-an-insurance-adjuster-do' },
            { id: 'i5', title: 'Replacement cost vs actual cash value', slug: 'replacement-cost-vs-actual-cash-value' },
            { id: 'i6', title: 'Does filing a claim raise premiums?', slug: 'does-filing-a-claim-raise-premiums' },
            { id: 'i7', title: 'What damages are excluded from homeowners insurance?', slug: 'what-damages-are-excluded-from-homeowners-insurance' },
            { id: 'i8', title: 'Can insurance cancel coverage after a claim?', slug: 'can-insurance-cancel-coverage-after-a-claim' },
            { id: 'i9', title: 'What is subrogation in homeowners insurance?', slug: 'what-is-subrogation-in-homeowners-insurance' },
            { id: 'i10', title: 'What if insurance payout is less than repair cost?', slug: 'what-if-insurance-payout-is-less-than-repair-cost' },
            { id: 'i11', title: 'Water damage vs flood damage explained', slug: 'water-damage-vs-flood-damage-explained' },
            { id: 'i12', title: 'Mold coverage explained', slug: 'mold-coverage-explained' },
            { id: 'i13', title: 'Fire damage claim process', slug: 'fire-damage-claim-process' },
            { id: 'i14', title: 'What is loss of use coverage?', slug: 'what-is-loss-of-use-coverage' },
            { id: 'i15', title: 'How insurance depreciation works', slug: 'how-insurance-depreciation-works' },
            { id: 'i16', title: 'When insurance disputes go to appraisal', slug: 'when-insurance-disputes-go-to-appraisal' },
            { id: 'i17', title: 'What happens if claim is delayed?', slug: 'what-happens-if-claim-is-delayed' },
            { id: 'i18', title: 'What documents insurers request', slug: 'what-documents-insurers-request' },
            { id: 'i19', title: 'Can you reopen a closed claim?', slug: 'can-you-reopen-a-closed-claim' },
            { id: 'i20', title: 'How insurance settlement timelines work', slug: 'how-insurance-settlement-timelines-work' },
        ]
    },
    {
        topicSlug: 'escrow',
        title: 'Escrow, Title & Closing',
        items: [
            { id: 'e1', title: 'How long does escrow take in California?', slug: 'how-long-does-escrow-take-california' },
            { id: 'e2', title: 'What happens after escrow opens?', slug: 'what-happens-after-escrow-opens' },
            { id: 'e3', title: 'What delays escrow closing?', slug: 'what-delays-escrow-closing' },
            { id: 'e4', title: 'What does “clear to close” mean?', slug: 'what-does-clear-to-close-mean' },
            { id: 'e5', title: 'What is a preliminary title report?', slug: 'what-is-a-preliminary-title-report' },
            { id: 'e6', title: 'Common title defects explained', slug: 'common-title-defects-explained' },
            { id: 'e7', title: 'Can escrow close without repairs?', slug: 'can-escrow-close-without-repairs' },
            { id: 'e8', title: 'What happens if escrow doesn’t close on time?', slug: 'what-happens-if-escrow-doesnt-close-on-time' },
            { id: 'e9', title: 'Who chooses the title company?', slug: 'who-chooses-the-title-company' },
            { id: 'e10', title: 'What happens if buyer backs out during escrow?', slug: 'what-happens-if-buyer-backs-out-during-escrow' },
            { id: 'e11', title: 'What is a final walkthrough?', slug: 'what-is-a-final-walkthrough' },
            { id: 'e12', title: 'Can seller cancel escrow?', slug: 'can-seller-cancel-escrow' },
            { id: 'e13', title: 'What happens if appraisal comes in low?', slug: 'what-happens-if-appraisal-comes-in-low' },
            { id: 'e14', title: 'What contingencies protect buyers?', slug: 'what-contingencies-protect-buyers' },
            { id: 'e15', title: 'What happens after offer acceptance?', slug: 'what-happens-after-offer-acceptance' },
            { id: 'e16', title: 'Can seller refuse repairs?', slug: 'can-seller-refuse-repairs' },
            { id: 'e17', title: 'How escrow instructions work', slug: 'how-escrow-instructions-work' },
            { id: 'e18', title: 'What happens at recording?', slug: 'what-happens-at-recording' },
            { id: 'e19', title: 'What happens after closing?', slug: 'what-happens-after-closing' },
            { id: 'e20', title: 'How escrow fees are calculated', slug: 'how-escrow-fees-are-calculated' },
        ]
    },
    {
        topicSlug: 'property-taxes',
        title: 'Property Taxes & Assessments',
        items: [
            { id: 't1', title: 'What happens if property taxes go unpaid?', slug: 'what-happens-if-property-taxes-go-unpaid' },
            { id: 't2', title: 'How long before a tax lien is placed?', slug: 'how-long-before-a-tax-lien-is-placed' },
            { id: 't3', title: 'What is a supplemental tax bill in California?', slug: 'supplemental-tax-bill-california' },
            { id: 't4', title: 'Why did my property taxes increase suddenly?', slug: 'why-did-my-property-taxes-increase-suddenly' },
            { id: 't5', title: 'What triggers reassessment?', slug: 'what-triggers-reassessment' },
            { id: 't6', title: 'What happens after filing a tax appeal?', slug: 'what-happens-after-filing-a-tax-appeal' },
            { id: 't7', title: 'Can property taxes be deferred?', slug: 'can-property-taxes-be-deferred' },
            { id: 't8', title: 'What is a tax-defaulted property?', slug: 'what-is-a-tax-defaulted-property' },
            { id: 't9', title: 'How property tax penalties work', slug: 'how-property-tax-penalties-work' },
            { id: 't10', title: 'How to read a property tax bill', slug: 'how-to-read-a-property-tax-bill' },
            { id: 't11', title: 'What exemptions reduce property taxes?', slug: 'what-exemptions-reduce-property-taxes' },
            { id: 't12', title: 'What happens after tax sale?', slug: 'what-happens-after-tax-sale' },
            { id: 't13', title: 'Property tax vs special assessments', slug: 'property-tax-vs-special-assessments' },
            { id: 't14', title: 'How inheritance affects property taxes', slug: 'how-inheritance-affects-property-taxes' },
            { id: 't15', title: 'Proposition 13 explained (procedural)', slug: 'proposition-13-explained' },
        ]
    },
    {
        topicSlug: 'repairs-liability',
        title: 'Maintenance, Liability & Disputes',
        items: [
            { id: 'm1', title: 'Who pays for fence repairs between neighbors?', slug: 'who-pays-for-fence-repairs' },
            { id: 'm2', title: 'Who is responsible for sidewalk injuries?', slug: 'homeowner-liability-sidewalk-injuries' },
            { id: 'm3', title: 'Does homeowners insurance cover water leaks?', slug: 'does-homeowners-insurance-cover-water-leaks' },
            { id: 'm4', title: 'Who pays for sewer line repairs?', slug: 'who-pays-for-sewer-line-repairs' },
            { id: 'm5', title: 'What happens if unpermitted work is discovered?', slug: ' what-happens-if-unpermitted-work-is-discovered' },
            { id: 'm6', title: 'Who is liable for tree damage?', slug: 'who-is-liable-for-tree-damage' },
            { id: 'm7', title: 'Shared driveway maintenance rules', slug: 'shared-driveway-maintenance-rules' },
            { id: 'm8', title: 'What is normal wear and tear?', slug: 'what-is-normal-wear-and-tear' },
            { id: 'm9', title: 'Mold liability between parties', slug: 'mold-liability-between-parties' },
            { id: 'm10', title: 'What happens if contractor damages property?', slug: 'what-happens-if-contractor-damages-property' },
            { id: 'm11', title: 'Can homeowner be sued for injuries?', slug: 'can-homeowner-be-sued-for-injuries' },
            { id: 'm12', title: 'What happens after a code violation notice?', slug: 'what-happens-after-a-code-violation-notice' },
            { id: 'm13', title: 'How building permits affect resale', slug: 'how-building-permits-affect-resale' },
            { id: 'm14', title: 'Boundary disputes explained', slug: 'boundary-disputes-explained' },
            { id: 'm15', title: 'Easement disputes explained', slug: 'easement-disputes-explained' },
        ]
    }
];
